haproxy:
  image: haproxy:1.5
  ports:
   - "1936:1936"
   - "8080:8080"
  volumes:
   - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  links:
   - php
php:
  image: andrewprice/php-arrestdb
  volumes:
   - ./php/html:/var/www/html/
  links:
   - mariadb
mariadb:
  image: mariadb
  environment:
   - MYSQL_DATABASE=api
   - MYSQL_USER=root
   - MYSQL_ROOT_PASSWORD=Password123
   - TERM=dumb
  volumes:
   - /var/container-data/arrestdb:/var/lib/mysql:rw
   - ./mariadb/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
