apiVersion: v1
kind: Service
metadata:
  name: andrpric-svc
  labels:
    app: arrestdb-pod
spec:
  type: NodePort
  selector:
    app: arrestdb-pod
  ports:
  - name: http
    protocol: TCP
    port: 80
  - name: sql
    protocol: TCP
    port: 3306
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: andrpric-rc
spec:
  replicas: 1
  selector:
    app: arrestdb-pod
  template:
    metadata:
      name: arrestdb-pod
      labels:
        app: arrestdb-pod
    spec:
      containers:
      - name: arrestdb-pod-web
        image: andrewprice/k8s-arrestdb-php-localhost
        ports:
        - containerPort: 80
      - name: arrestdb-pod-sql
        image: andrewprice/k8s-arrestdb-mariadb
        ports:
        - containerPort: 3306
