apiVersion: v1
kind: Service
metadata:
  name: andrpric-arrestdb-svc
  labels:
    app: arrestdb-sql
spec:
  type: NodePort
  selector:
    app: arrestdb-sql
  ports:
  - protocol: TCP
    port: 3306
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: andrpric-arrestdb-rc
spec:
  replicas: 1
  selector:
    app: arrestdb-sql
  template:
    metadata:
      name: arrestdb-sql
      labels:
        app: arrestdb-sql
    spec:
      containers:
      - name: k8s-arrestdb-mariadb
        image: andrewprice/k8s-arrestdb-mariadb
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: andrpric-arrestdb-svc-fe
  labels:
    app: arrestdb-php
spec:
  type: NodePort
  selector:
    app: arrestdb-php
  ports:
  - protocol: TCP
    port: 80
    nodePort: 31234
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: andrpric-arrestdb-rc-fe
spec:
  replicas: 3
  selector:
    app: arrestdb-php
  template:
    metadata:
      name: arrestdb-php
      labels:
        app: arrestdb-php
    spec:
      containers:
      - name: k8s-arrestdb-php
        image: andrewprice/k8s-arrestdb-php
        ports:
        - containerPort: 80
